char* string_join(int count, ...);
void string_remove_newline(char *str);
void dir_create(const char *dir);
void file_delete(const char *path);
int file_is_png(char *file);
unsigned long file_size(char* file);
void logcat_add(char *str1, char *str2, char *str3);
void logcat_add_real(char *str1, int real1, char *str2);
int point_in_rectangle(int px, int py, int x1, int y1, int x2, int y2);
void getDateString(char *string, int date_format, SceDateTime *time);
void getTimeString(char *string, int time_format, SceDateTime *time);
